### ISSUE TITLE
Just 1 value? Do we not care about minority speakers then?

### ISSUE THREAD

**Issue by muster-mark** [Tanych/accept-language#7]
You say "Since servers usually don't need to know the full list of languages the user accepts during content negotiation". That is correct, because most website visits are either by people who speak English visiting sites that are by default served in English, or by people who read Chinese characters visiting sites that are by default served in Chinese.

This is not going to help people who speak minority languages. Surely 3 or even 2 values would make a dent in the entropy without making things difficult for them.

I do wonder if the quality factors are needed. Surely the order is all that matters?

**Comment by Tanych** [comment]
Thanks for your question. We do care about minority speakers.  Browser will  potential resend the request (after content negotiation) to get a better representation if site supports user's other accept language.  https://github.com/Tanych/accept-language#language-negotiation

**Comment by muster-mark** [comment]
Ah ok apologies. I did not see that.
